definitions:
  dto.GetOtpRequest:
    properties:
      mobile_number:
        maxLength: 11
        minLength: 11
        type: string
    required:
    - mobile_number
    type: object
  dto.LoginByUsernameRequest:
    properties:
      password:
        minLength: 6
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  dto.RegisterLoginByMobileNumber:
    properties:
      mobileNumber:
        maxLength: 11
        minLength: 11
        type: string
      otp:
        maxLength: 6
        minLength: 6
        type: string
    required:
    - mobileNumber
    - otp
    type: object
  dto.RegisterUserByUsernameRequest:
    properties:
      email:
        minLength: 6
        type: string
      firstName:
        minLength: 3
        type: string
      lastName:
        minLength: 3
        type: string
      password:
        minLength: 6
        type: string
      username:
        minLength: 5
        type: string
    required:
    - email
    - firstName
    - lastName
    - password
    - username
    type: object
  handlers.Person:
    properties:
      first_name:
        type: string
      last_name:
        type: string
      phone:
        type: string
    required:
    - first_name
    - phone
    type: object
  helper.BaseHttpResponse:
    properties:
      error: {}
      result: {}
      resultCode:
        type: integer
      success:
        type: boolean
      validationErrors:
        items:
          $ref: '#/definitions/validations.ValidationError'
        type: array
    type: object
  validations.ValidationError:
    properties:
      message:
        type: string
      property:
        type: string
      tag:
        type: string
      value:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/health/:
    get:
      consumes:
      - application/json
      description: regiser user
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/helper.BaseHttpResponse'
        "400":
          description: Failure
          schema:
            $ref: '#/definitions/helper.BaseHttpResponse'
      summary: register
      tags:
      - register_user
    post:
      consumes:
      - application/json
      description: HealthPost
      parameters:
      - description: person data
        in: body
        name: person
        required: true
        schema:
          $ref: '#/definitions/handlers.Person'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/helper.BaseHttpResponse'
        "400":
          description: Failure
          schema:
            $ref: '#/definitions/helper.BaseHttpResponse'
      summary: HealthPost
      tags:
      - HealthPost
  /v1/users/login-by-mobile/:
    post:
      consumes:
      - application/json
      description: send otp to user
      parameters:
      - description: RegisterByUsernameRequest
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterLoginByMobileNumber'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/helper.BaseHttpResponse'
        "400":
          description: Failure
          schema:
            $ref: '#/definitions/helper.BaseHttpResponse'
        "409":
          description: Failure
          schema:
            $ref: '#/definitions/helper.BaseHttpResponse'
      summary: Send Otp To User
      tags:
      - users
  /v1/users/login-by-username/:
    post:
      consumes:
      - application/json
      description: send otp to user
      parameters:
      - description: LoginByUsernameRequest
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.LoginByUsernameRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/helper.BaseHttpResponse'
        "400":
          description: Failure
          schema:
            $ref: '#/definitions/helper.BaseHttpResponse'
        "409":
          description: Failure
          schema:
            $ref: '#/definitions/helper.BaseHttpResponse'
      summary: Send Otp To User
      tags:
      - users
  /v1/users/register-by-username/:
    post:
      consumes:
      - application/json
      description: send otp to user
      parameters:
      - description: RegisterUserByUsernameRequest
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterUserByUsernameRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/helper.BaseHttpResponse'
        "400":
          description: Failure
          schema:
            $ref: '#/definitions/helper.BaseHttpResponse'
        "409":
          description: Failure
          schema:
            $ref: '#/definitions/helper.BaseHttpResponse'
      summary: Send Otp To User
      tags:
      - users
  /v1/users/send-otp/:
    post:
      consumes:
      - application/json
      description: send otp to user
      parameters:
      - description: get otp request
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.GetOtpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/helper.BaseHttpResponse'
        "400":
          description: Failure
          schema:
            $ref: '#/definitions/helper.BaseHttpResponse'
        "409":
          description: Failure
          schema:
            $ref: '#/definitions/helper.BaseHttpResponse'
      summary: Send Otp To User
      tags:
      - users
swagger: "2.0"
