Server:
    Port: 8000
    RunMod: debug
    timeZone: Asia/Tehran
Logger:
    filePath: ../logs/logs.log
    Encoding: json
    level: debug
cors:
    allowOrigins: "*"
Postgres:
    host: localhost
    port: 5432
    user: postgres
    password: admin
    dbName: car_sale_db
    sslMode: disable
    maxIdleConnection: 10
    maxOpenConnections: 100
    connMaxLifetime: 5
Redis:
    host: localhost
    port: 6379
    password: password
    db: 0
    dialTimeout: 5
    readTimeout: 5
    writeTimeout: 5
    poolSize: 10
    poolTimeout: 15
    IdleCheckFrequency: 500
Password:
    includeChars: true
    includeDigits: true
    minLength: 6
    maxLength: 64
    includeUppercase: true
    includeLowercase: true

