name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.5'  # Make sure this matches your `go.mod` file

    - name: Verify Go version
      run: go version

    - name: Install dependencies
      run: |
        cd src
        go mod tidy
        go mod download

    - name: Build project
      run: cd src && go build -v cmd/main.go

    - name: Run tests
      run: |
        cd src
        go test -v ./...
